version: '3.2'

services:
    redis:
        build: ./redis

    postgres:
        image: postgis/postgis:11-3.0
        environment:
          - "POSTGRES_USER=postgres"
          - "POSTGRES_PASSWORD=password"
          - "POSTGRES_DB=django_test"

    nginx:
        image: isptoolbox-nginx
        build: ./nginx
        depends_on:
            - django-app
            - websocket-app
            - flower
        ports:
            - 80:80

    celery:
        image: isptoolbox-celery
        build: ./webserver
        command: celery worker --beat -A webserver -l info
        depends_on:
            - redis
            - postgres
        environment:
            - REDIS_BACKEND=redis://redis:6379
            - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/dataUpdate/config/gcp-service-key.json

    django-app:
        image: isptoolbox-django
        build: ./webserver
        command: gunicorn webserver.wsgi -b 0.0.0.0 -w 2
        depends_on:
            - redis
            - postgres
        environment:
            - REDIS_BACKEND=redis://redis:6379

    node:
        image: isptoolbox-node
        build: ./node-webserver
        depends_on:
            - redis
        environment:
            - REDIS_BACKEND=redis://redis:6379
    
    websocket-app:
        image: isptoolbox-django-ws
        build: ./webserver
        command: daphne webserver.asgi:application -b 0.0.0.0 -p 8010 --access-log -
        depends_on:
            - redis
            - postgres
        environment:
            - REDIS_BACKEND=redis://redis:6379
    
    flower:
        image: isptoolbox-flower
        build: ./webserver
        command: celery flower -A webserver --address=0.0.0.0 --port=5555 --broker=redis://redis:6379 --url_prefix=async
        depends_on:
            - redis
        ports:
            - 5555:5555