version: "3.2"

services:
  redis:
    build: ./redis
    logging:
      driver: "none"

  postgres:
    image: postgis/postgis:11-3.0
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=django_test"

  nginx:
    image: isptoolbox-nginx
    build: ./nginx
    depends_on:
      - django-app
      - websocket-app
      - flower
      - node-app
    ports:
      - 80:80

  celery:
    image: isptoolbox-celery
    build: ./webserver
    command: celery --app webserver worker -l info
    depends_on:
      - redis
      - postgres
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/dataUpdate/config/gcp-service-key.json

  django-app:
    image: isptoolbox-django
    build: ./webserver
    command: gunicorn webserver.wsgi -b 0.0.0.0 -w 2
    depends_on:
      - redis
      - postgres

  node-app:
    image: isptoolbox-node
    build: ./node-webserver
    depends_on:
      - redis

  websocket-app:
    image: isptoolbox-django-ws
    build: ./webserver
    command: daphne webserver.asgi:application -b 0.0.0.0 -p 8010 --access-log -
    depends_on:
      - redis
      - postgres

  flower:
    image: isptoolbox-flower
    build: ./webserver
    command: celery --app webserver flower --conf=flower_config.py
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555
