version: "3.2"

services:
  static:
    command: ["/bin/sh", "-c", "/usr/src/app/watch_static_dev.sh"]
    build: ./webserver/static
    volumes:
      - ./webserver/static:/usr/src/app

  django-app:
    entrypoint: ["/usr/bin/tini", "-g", "--"]
    command: ["/bin/sh", "-c", "/usr/src/app/test_entrypoint_django.sh"]
    environment:
      COVERAGE_RCFILE: "/usr/src/app/.coveragerc-base"
      COVERAGE_PROCESS_START: "/usr/src/app/.coveragerc-base"
      DEBUG: "TRUE"
      POSTGRES_DB: "postgres"
      DB_NAME: "django_test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
    volumes:
      - ./webserver:/usr/src/app
      - ./coverage:/opt/coverage
      - ./scripts:/opt/scripts
    ports:
      - 3000:3000
      - 8000:8000
    stop_signal: SIGINT
    depends_on:
      - static

  celery:
    entrypoint: ["/usr/bin/tini", "-g", "--"]
    command: ["/bin/sh", "-c", "/usr/src/app/test_entrypoint_celery.sh"]
    environment:
      COVERAGE_RCFILE: "/usr/src/app/.coveragerc-base"
      COVERAGE_PROCESS_START: "/usr/src/app/.coveragerc-base"
      POSTGRES_DB: "postgres"
    stop_signal: SIGINT
    volumes:
      - ./webserver:/usr/src/app
      - ./coverage:/opt/coverage
      - ./scripts:/opt/scripts

  node-app:
    command: ["npm", "run", "start", "--", "8020"]
    ports:
      - 8020:8020
