version: '3'

services:
  django-app:
    command: /bin/sh -c "/usr/src/app/dev_entrypoint_django.sh"
    environment:
      DEBUG: 'TRUE'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./webserver:/usr/src/app
    ports:
      - 3000:3000
      - 8000:8000
  celery:
    environment:
      POSTGRES_DB: 'postgres'