version: '3'

services:
    deepgis:
        build: ./webserver
        volumes:
            - ./webserver:/usr/src/app
        ports:
            - 8020:80
    # homespassed:
    #     build: ./house_counter
    #     ports:
    #         - 8010:80      
    nginx:
        build: ./nginx
        ports:
            - 80:80
        expose:
            - 8020
        depends_on:
            - deepgis
    celery:
        build: ./webserver
        command: celery -A webserver worker -l info
        volumes:
            - ./webserver/:/usr/src/app/
        environment:
            - DJANGO_SETTINGS_MODULE=webserver.settings_prod