version: "3.2"

services:
  static:
    command: /bin/sh -c "/usr/src/app/watch_static_dev.sh"
    build: ./webserver/static
    volumes:
      - ./webserver/static:/usr/src/app
  django-app:
    command: /bin/sh -c "/usr/src/app/dev_entrypoint_django.sh"
    environment:
      COVERAGE_RCFILE: "/opt/.coveragerc"
      DEBUG: "TRUE"
    volumes:
      - ./webserver:/usr/src/app
      - ./coverage:/opt/coverage
      - ./scripts:/opt/scripts
    ports:
      - 3000:3000
      - 8000:8000
    depends_on:
      - static
  celery:
    command: /bin/sh -c "/usr/src/app/dev_entrypoint_celery.sh"
    environment:
      DEBUG: "TRUE"
    volumes:
      - ./webserver:/usr/src/app
  node-app:
    ports:
      - 8020:8020
    volumes:
      - ./node-webserver:/usr/src/app
