version: '3.2'

services:
  static:
    command: /bin/sh -c "/usr/src/app/watch_static_dev.sh"
    build: ./webserver/static
    volumes:
      - ./webserver/static:/usr/src/app
  django-app:
    command: /bin/sh -c "/usr/src/app/dev_entrypoint_django.sh"
    environment:
      DEBUG: 'TRUE'
      POSTGRES_DB: 'postgres'
      DB_NAME: "django_test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
    volumes:
      - ./webserver:/usr/src/app
    ports:
      - 3000:3000
      - 8000:8000
    depends_on:
      - static
  celery:
    command: /bin/sh -c "/usr/src/app/dev_entrypoint_celery.sh"
    environment:
      POSTGRES_DB: 'postgres'
    volumes:
      - ./webserver:/usr/src/app
  node:
    ports:
      - 8080:8080
    volumes:
      - ./node-webserver:/usr/src/app