version: '3'

services:
    deepgis:
        build: ./webserver
        volumes:
            - ./webserver:/usr/src/app
        ports:
            - 80:80
    # homespassed:
    #     build: ./house_counter
    #     ports:
    #         - 8010:80      
    # nginx:
    #     build: ./nginx
    #     ports:
    #         - 80:80
    #     expose:
    #         - 8010
    #         - 8020
    #     depends_on:
    #         - homespassed
    #         - deepgis