version: '3'

services:
    webserver:
        image: isptoolbox-django
        build: ./webserver
        volumes:
            - ./webserver:/usr/src/app
        expose:
            - 8020
    nginx:
        image: isptoolbox-nginx
        build: ./nginx
        ports:
            - 80:80
        expose:
            - 8020
        depends_on:
            - webserver
    celery:
        image: isptoolbox-celery
        build: ./webserver
        command: celery -A webserver worker -l info
        volumes:
            - ./webserver/:/usr/src/app/
        environment:
            - DJANGO_SETTINGS_MODULE=webserver.settings_prod