version: '3'

services:
    django-app:
        image: isptoolbox-django
        build: ./webserver
        volumes:
            - ./webserver:/usr/src/app
        ports:
            - 80:80
        command: gunicorn webserver.wsgi -b 0.0.0.0 -w 6
        environment:
            - DJANGO_SETTINGS_MODULE=webserver.settings_prod
    nginx:
        image: isptoolbox-nginx
        build: ./nginx
        network_mode: 'service:django-app'
        depends_on:
            - django-app
    celery:
        image: isptoolbox-celery
        build: ./webserver
        command: celery -A webserver worker -l info
        volumes:
            - ./webserver/:/usr/src/app/
        environment:
            - DJANGO_SETTINGS_MODULE=webserver.settings_prod