version: '3'

services:
    redis:
        build: ./redis

    postgres:
        image: postgis/postgis:11-3.0
        environment:
          - "POSTGRES_USER=postgres"
          - "POSTGRES_PASSWORD=password"
          - "POSTGRES_DB=django_test"

    nginx:
        image: isptoolbox-nginx
        build: ./nginx
        depends_on:
            - django-app
        ports:
            - 80:80

    celery:
        image: isptoolbox-celery
        build: ./webserver
        command: celery worker -A webserver -l info
        depends_on:
            - redis
            - postgres
        environment:
            - REDIS_BACKEND=redis://redis:6379

    django-app:
        image: isptoolbox-django
        build: ./webserver
        command: gunicorn webserver.wsgi -b 0.0.0.0 -w 2
        depends_on:
            - redis
            - postgres
        environment:
            - REDIS_BACKEND=redis://redis:6379