name: E2E Cypress Testing
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install make
        run: |
          sudo apt-get update && sudo apt-get install -y make
      - name: Build Docker Containers
        run: |
          make setup_dev
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: make run_dev
          wait-on: 'http://localhost:8000'
          # wait for 3 minutes for the server to respond
          wait-on-timeout: 180