name: E2E Cypress Testing
on:
  pull_request:
    types: [review_requested, edited, synchronize, opened]
    branches:
      - master
jobs:
  cypress-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install make + cypress
        run: |
          sudo apt-get update && sudo apt-get install -y make
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          sudo apt install -y nodejs npm
          npm install cypress --save-dev
          pip3 install coverage==5.5
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Containers
        run: |
          make setup_dev
          make default_objects
          make static_test
          docker stop $(docker ps -a -f "name=isptoolbox_" -q)
      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        with:
          start: make run_test
          wait-on: "http://localhost:8000"
      - name: Generate E2E test backend coverage
        run: |
          cd webserver
          python3 scripts/create_coverage_file.py .coveragerc-base .coveragerc-dev .coveragerc
          coverage combine
          coverage report
          coverage html
          coverage erase
      - name: Upload E2E test backend coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage-python-htmlcov
          path: coverage/htmlcov
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
